language: php
php:
  - 7.0
  - 5.6
  - hhvm
  - hhvm-nightly
matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
  fast_finish: true
before_script:
  - composer self-update
  - composer -vvv install --prefer-source --no-interaction
script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then vendor/bin/phpunit --verbose; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/phpunit --verbose --coverage-text --coverage-clover /tmp/coverage/coverage.xml; fi;'
notififation:
  on_success: never
  on_failure: always
