language: php
php:
  - 7.0
  - 5.6
  - hhvm
  - hhvm-nightly
matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
  fast_finish: true
before_script:
  - composer self-update
  - composer -vvv install --prefer-source --no-interaction
script:
  - ./.pupunit
notififation:
  on_success: never
  on_failure: always
